trigger:
  - main
  
pool: 'Azure Pipelines'

variables:
  WEB_APPS_API_TOKEN: $(AZURE_STATIC_WEB_APPS_API_TOKEN)

jobs:
- job: 'BuildAndDeploy'
  steps:
  - task: AzureStaticWebApp@0
    inputs:
      skip_app_build: true
      skip_api_build: true
      output_location: '$(System.DefaultWorkingDirectory)/'
      azure_static_web_apps_api_token: $(WEB_APPS_API_TOKEN)
